workflow_details:
  name: "Community Engagement"
  description: ""

er_client:
  data_source:
    name: "olokeri"  # EarthRanger data source name (e.g. "mysite")

time_range:
  timezone:
    label: Africa/Nairobi
    tzCode: EAT
    name: Nairobi
    utc: +03:00
  since: "2000-01-01T00:00:00.000Z"
  until: "2026-12-31T23:59:59.000Z"

groupers:
  groupers:
    - temporal_index: "__quarter__"
#     - temporal_index: "%Y-%m"
#     - index_name: meeting_location_level_one

events:
  event_types:
    - "community_meeting_new"  # EarthRanger event type name for community engagement events

# feature_group_name:  # uncomment when choropleth is re-enabled
#   var: ""  # Feature group name in EarthRanger (e.g. adjudication areas, chiefdoms, forest clusters)

generate_report:
  template_path: "/Users/zak/Documents/w-dynamics/eden-community_engagement/resources/templates/community_engagement_report_template.docx"
