# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Community Engagement
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope_workflows_ext_custom.tasks.io import get_current_user as get_current_user
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_text_layer_pydeck as create_text_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_boxplot as draw_boxplot
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_pie_chart as draw_pie_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_eden.tasks import add_temporal_idx as add_temporal_idx
from ecoscope_workflows_ext_eden.tasks import (
    apply_choropleth_colormap as apply_choropleth_colormap,
)
from ecoscope_workflows_ext_eden.tasks import (
    build_topic_location_table as build_topic_location_table,
)
from ecoscope_workflows_ext_eden.tasks import compute_median as compute_median
from ecoscope_workflows_ext_eden.tasks import (
    create_viewstate_gdf as create_viewstate_gdf,
)
from ecoscope_workflows_ext_eden.tasks import (
    draw_topic_bar_chart as draw_topic_bar_chart,
)
from ecoscope_workflows_ext_eden.tasks import exclude_groupers as exclude_groupers
from ecoscope_workflows_ext_eden.tasks import (
    expand_to_composite_keys as expand_to_composite_keys,
)
from ecoscope_workflows_ext_eden.tasks import (
    generate_community_report as generate_community_report,
)
from ecoscope_workflows_ext_eden.tasks import get_er_site_url as get_er_site_url
from ecoscope_workflows_ext_eden.tasks import (
    join_meeting_counts_to_polygons as join_meeting_counts_to_polygons,
)
from ecoscope_workflows_ext_eden.tasks import (
    load_adjudication_polygons as load_adjudication_polygons,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_count_labels as prepare_count_labels,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_gender_breakdown as prepare_gender_breakdown,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_missing_location_events as prepare_missing_location_events,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_polygon_labels as prepare_polygon_labels,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_params = dict(
    data_source=...,
)

# %%
# call the task


er_client = (
    set_er_connection.set_task_instance_id("er_client")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**er_client_params)
    .call()
)


# %% [markdown]
# ## Current User

# %%
# parameters

user_details_params = dict()

# %%
# call the task


user_details = (
    get_current_user.set_task_instance_id("user_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=er_client, **user_details_params)
    .call()
)


# %% [markdown]
# ## ER Site URL

# %%
# parameters

er_site_url_params = dict()

# %%
# call the task


er_site_url = (
    get_er_site_url.set_task_instance_id("er_site_url")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(client=er_client, **er_site_url_params)
    .call()
)


# %% [markdown]
# ## Define Base Maps

# %%
# parameters

base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


base_maps = (
    set_base_maps_pydeck.set_task_instance_id("base_maps")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**base_maps_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

get_timezone_params = dict()

# %%
# call the task


get_timezone = (
    get_timezone_from_time_range.set_task_instance_id("get_timezone")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(time_range=time_range, **get_timezone_params)
    .call()
)


# %% [markdown]
# ## Set Groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Get Community Engagement Events

# %%
# parameters

events_params = dict(
    event_types=...,
)

# %%
# call the task


events = (
    get_events.set_task_instance_id("events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        client=er_client,
        time_range=time_range,
        event_columns=[
            "id",
            "time",
            "event_type",
            "location",
            "geometry",
            "event_details",
            "state",
            "serial_number",
        ],
        include_details=True,
        raise_on_empty=False,
        include_updates=False,
        include_null_geometry=True,
        include_display_values=True,
        include_related_events=False,
        **events_params,
    )
    .call()
)


# %% [markdown]
# ## Filter Resolved Events

# %%
# parameters

resolved_events_params = dict()

# %%
# call the task


resolved_events = (
    filter_row_values.set_task_instance_id("resolved_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=events, column="state", values=["resolved"], **resolved_events_params)
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

events_tz_params = dict()

# %%
# call the task


events_tz = (
    convert_values_to_timezone.set_task_instance_id("events_tz")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=resolved_events, timezone=get_timezone, columns=["time"], **events_tz_params
    )
    .call()
)


# %% [markdown]
# ## Process Event Details

# %%
# parameters

processed_events_params = dict()

# %%
# call the task


processed_events = (
    process_events_details.set_task_instance_id("processed_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=events_tz,
        client=er_client,
        map_to_titles=False,
        ordered=True,
        **processed_events_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

extract_participants_total_params = dict()

# %%
# call the task


extract_participants_total = (
    extract_value_from_json_column.set_task_instance_id("extract_participants_total")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=processed_events,
        column_name="event_details",
        field_name_options=["participants_total"],
        output_column_name="participants_total",
        output_type="float",
        **extract_participants_total_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

extract_participants_men_params = dict()

# %%
# call the task


extract_participants_men = (
    extract_value_from_json_column.set_task_instance_id("extract_participants_men")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_participants_total,
        column_name="event_details",
        field_name_options=["participants_men"],
        output_column_name="participants_men",
        output_type="float",
        **extract_participants_men_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

extract_participants_women_params = dict()

# %%
# call the task


extract_participants_women = (
    extract_value_from_json_column.set_task_instance_id("extract_participants_women")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_participants_men,
        column_name="event_details",
        field_name_options=["participants_women"],
        output_column_name="participants_women",
        output_type="float",
        **extract_participants_women_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

extract_youth_male_params = dict()

# %%
# call the task


extract_youth_male = (
    extract_value_from_json_column.set_task_instance_id("extract_youth_male")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_participants_women,
        column_name="event_details",
        field_name_options=["participants_youth_male"],
        output_column_name="participants_youth_male",
        output_type="float",
        **extract_youth_male_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

extract_youth_female_params = dict()

# %%
# call the task


extract_youth_female = (
    extract_value_from_json_column.set_task_instance_id("extract_youth_female")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_youth_male,
        column_name="event_details",
        field_name_options=["participants_youth_female"],
        output_column_name="participants_youth_female",
        output_type="float",
        **extract_youth_female_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

extract_location_one_params = dict()

# %%
# call the task


extract_location_one = (
    extract_value_from_json_column.set_task_instance_id("extract_location_one")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_youth_female,
        column_name="event_details",
        field_name_options=["meeting_location_level_one"],
        output_column_name="meeting_location_level_one",
        output_type="str",
        **extract_location_one_params,
    )
    .call()
)


# %% [markdown]
# ## Add Temporal Index

# %%
# parameters

events_with_temporal_index_params = dict()

# %%
# call the task


events_with_temporal_index = (
    add_temporal_idx.set_task_instance_id("events_with_temporal_index")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=extract_location_one,
        time_col="time",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **events_with_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Split by Groupers

# %%
# parameters

grouped_events_params = dict()

# %%
# call the task


grouped_events = (
    split_groups.set_task_instance_id("grouped_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(df=events_with_temporal_index, groupers=groupers, **grouped_events_params)
    .call()
)


# %% [markdown]
# ## Total Meetings Count

# %%
# parameters

total_meetings_params = dict()

# %%
# call the task


total_meetings = (
    dataframe_count.set_task_instance_id("total_meetings")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**total_meetings_params)
    .mapvalues(argnames=["df"], argvalues=grouped_events)
)


# %% [markdown]
# ## Total Meetings Widget

# %%
# parameters

total_meetings_widget_params = dict()

# %%
# call the task


total_meetings_widget = (
    create_single_value_widget_single_view.set_task_instance_id("total_meetings_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Total Meetings", decimal_places=0, **total_meetings_widget_params)
    .map(argnames=["view", "data"], argvalues=total_meetings)
)


# %% [markdown]
# ## Total Meetings Merged

# %%
# parameters

total_meetings_merged_params = dict()

# %%
# call the task


total_meetings_merged = (
    merge_widget_views.set_task_instance_id("total_meetings_merged")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=total_meetings_widget, **total_meetings_merged_params)
    .call()
)


# %% [markdown]
# ## Total Participants Sum

# %%
# parameters

total_participants_params = dict()

# %%
# call the task


total_participants = (
    dataframe_column_sum.set_task_instance_id("total_participants")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column_name="participants_total", **total_participants_params)
    .mapvalues(argnames=["df"], argvalues=grouped_events)
)


# %% [markdown]
# ## Total Participants Widget

# %%
# parameters

total_participants_widget_params = dict()

# %%
# call the task


total_participants_widget = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_participants_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Participants", decimal_places=0, **total_participants_widget_params
    )
    .map(argnames=["view", "data"], argvalues=total_participants)
)


# %% [markdown]
# ## Total Participants Merged

# %%
# parameters

total_participants_merged_params = dict()

# %%
# call the task


total_participants_merged = (
    merge_widget_views.set_task_instance_id("total_participants_merged")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=total_participants_widget, **total_participants_merged_params)
    .call()
)


# %% [markdown]
# ## Median Participants per Meeting

# %%
# parameters

median_participants_params = dict()

# %%
# call the task


median_participants = (
    compute_median.set_task_instance_id("median_participants")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(column="participants_total", **median_participants_params)
    .mapvalues(argnames=["df"], argvalues=grouped_events)
)


# %% [markdown]
# ## Median Participants Widget

# %%
# parameters

median_participants_widget_params = dict()

# %%
# call the task


median_participants_widget = (
    create_single_value_widget_single_view.set_task_instance_id(
        "median_participants_widget"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Median Participants / Meeting",
        decimal_places=1,
        **median_participants_widget_params,
    )
    .map(argnames=["view", "data"], argvalues=median_participants)
)


# %% [markdown]
# ## Median Participants Merged

# %%
# parameters

median_participants_merged_params = dict()

# %%
# call the task


median_participants_merged = (
    merge_widget_views.set_task_instance_id("median_participants_merged")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=median_participants_widget, **median_participants_merged_params)
    .call()
)


# %% [markdown]
# ## Draw Participants Box Plot

# %%
# parameters

box_plot_params = dict(
    widget_id=...,
)

# %%
# call the task


box_plot = (
    draw_boxplot.set_task_instance_id("box_plot")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        y_column="participants_total",
        x_column=None,
        color_column=None,
        sort_by=None,
        sort_ascending=True,
        show_points="outliers",
        orientation="v",
        boxmode="overlay",
        boxmean=False,
        notched=False,
        reference_line=None,
        colormap="Paired",
        plot_style=None,
        layout_style={
            "title": None,
            "yaxis": {"title": "Participants"},
            "plot_bgcolor": "white",
        },
        **box_plot_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=grouped_events)
)


# %% [markdown]
# ## Persist Box Plot

# %%
# parameters

box_plot_html_params = dict(
    filename=...,
)

# %%
# call the task


box_plot_html = (
    persist_text.set_task_instance_id("box_plot_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="box_plot",
        **box_plot_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=box_plot)
)


# %% [markdown]
# ## Box Plot Widget

# %%
# parameters

box_plot_widget_params = dict()

# %%
# call the task


box_plot_widget = (
    create_plot_widget_single_view.set_task_instance_id("box_plot_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Participants per Meeting Distribution", **box_plot_widget_params)
    .map(argnames=["view", "data"], argvalues=box_plot_html)
)


# %% [markdown]
# ## Box Plot Merged

# %%
# parameters

box_plot_merged_params = dict()

# %%
# call the task


box_plot_merged = (
    merge_widget_views.set_task_instance_id("box_plot_merged")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=box_plot_widget, **box_plot_merged_params)
    .call()
)


# %% [markdown]
# ## Prepare Gender Breakdown

# %%
# parameters

gender_breakdown_params = dict()

# %%
# call the task


gender_breakdown = (
    prepare_gender_breakdown.set_task_instance_id("gender_breakdown")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        men_column="participants_men",
        women_column="participants_women",
        youth_men_column="participants_youth_male",
        youth_women_column="participants_youth_female",
        **gender_breakdown_params,
    )
    .mapvalues(argnames=["df"], argvalues=grouped_events)
)


# %% [markdown]
# ## Apply Gender Colors

# %%
# parameters

gender_colormap_params = dict()

# %%
# call the task


gender_colormap = (
    apply_color_map.set_task_instance_id("gender_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        input_column_name="category",
        output_column_name="gender_color",
        colormap="Paired",
        **gender_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=gender_breakdown)
)


# %% [markdown]
# ## Draw Gender Pie Chart

# %%
# parameters

gender_pie_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


gender_pie_chart = (
    draw_pie_chart.set_task_instance_id("gender_pie_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        value_column="count",
        label_column="category",
        color_column="gender_color",
        plot_style={"textinfo": "label+percent"},
        layout_style={"title": None},
        **gender_pie_chart_params,
    )
    .mapvalues(argnames=["dataframe"], argvalues=gender_colormap)
)


# %% [markdown]
# ## Persist Gender Pie Chart

# %%
# parameters

gender_pie_chart_html_params = dict(
    filename=...,
)

# %%
# call the task


gender_pie_chart_html = (
    persist_text.set_task_instance_id("gender_pie_chart_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="gender_pie_chart",
        **gender_pie_chart_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=gender_pie_chart)
)


# %% [markdown]
# ## Gender Pie Chart Widget

# %%
# parameters

gender_pie_chart_widget_params = dict()

# %%
# call the task


gender_pie_chart_widget = (
    create_plot_widget_single_view.set_task_instance_id("gender_pie_chart_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Men / Women / Youth Men / Youth Women", **gender_pie_chart_widget_params
    )
    .map(argnames=["view", "data"], argvalues=gender_pie_chart_html)
)


# %% [markdown]
# ## Gender Pie Chart Merged

# %%
# parameters

gender_pie_chart_merged_params = dict()

# %%
# call the task


gender_pie_chart_merged = (
    merge_widget_views.set_task_instance_id("gender_pie_chart_merged")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=gender_pie_chart_widget, **gender_pie_chart_merged_params)
    .call()
)


# %% [markdown]
# ## Draw Topic Bar Chart

# %%
# parameters

topic_bar_chart_params = dict(
    widget_id=...,
)

# %%
# call the task


topic_bar_chart = (
    draw_topic_bar_chart.set_task_instance_id("topic_bar_chart")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        event_details_column="event_details",
        location_column="meeting_location_level_one",
        topic_key="topics",
        topic_field="topic",
        title=None,
        x_axis_title="Location",
        y_axis_title="Frequency",
        colormap="Paired",
        **topic_bar_chart_params,
    )
    .mapvalues(argnames=["df"], argvalues=grouped_events)
)


# %% [markdown]
# ## Persist Topic Bar Chart

# %%
# parameters

topic_bar_chart_html_params = dict(
    filename=...,
)

# %%
# call the task


topic_bar_chart_html = (
    persist_text.set_task_instance_id("topic_bar_chart_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="topic_bar_chart",
        **topic_bar_chart_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=topic_bar_chart)
)


# %% [markdown]
# ## Topic Bar Chart Widget

# %%
# parameters

topic_bar_chart_widget_params = dict()

# %%
# call the task


topic_bar_chart_widget = (
    create_plot_widget_single_view.set_task_instance_id("topic_bar_chart_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Topics Covered by Location", **topic_bar_chart_widget_params)
    .map(argnames=["view", "data"], argvalues=topic_bar_chart_html)
)


# %% [markdown]
# ## Topic Bar Chart Merged

# %%
# parameters

topic_bar_chart_merged_params = dict()

# %%
# call the task


topic_bar_chart_merged = (
    merge_widget_views.set_task_instance_id("topic_bar_chart_merged")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=topic_bar_chart_widget, **topic_bar_chart_merged_params)
    .call()
)


# %% [markdown]
# ## Build Topic Location Pivot

# %%
# parameters

topic_location_pivot_params = dict()

# %%
# call the task


topic_location_pivot = (
    build_topic_location_table.set_task_instance_id("topic_location_pivot")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        event_details_column="event_details",
        location_column="meeting_location_level_one",
        topic_key="topics",
        topic_field="topic",
        **topic_location_pivot_params,
    )
    .mapvalues(argnames=["df"], argvalues=grouped_events)
)


# %% [markdown]
# ## Load Adjudication Polygons

# %%
# parameters

adjudication_polygons_params = dict()

# %%
# call the task


adjudication_polygons = (
    load_adjudication_polygons.set_task_instance_id("adjudication_polygons")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**adjudication_polygons_params)
    .call()
)


# %% [markdown]
# ## Choropleth Groupers

# %%
# parameters

choropleth_groupers_params = dict()

# %%
# call the task


choropleth_groupers = (
    exclude_groupers.set_task_instance_id("choropleth_groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        groupers=groupers,
        exclude=["meeting_location_level_one"],
        **choropleth_groupers_params,
    )
    .call()
)


# %% [markdown]
# ## Split Choropleth Events

# %%
# parameters

choropleth_events_params = dict()

# %%
# call the task


choropleth_events = (
    split_groups.set_task_instance_id("choropleth_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        df=events_with_temporal_index,
        groupers=choropleth_groupers,
        **choropleth_events_params,
    )
    .call()
)


# %% [markdown]
# ## Join Meeting Counts to Polygons

# %%
# parameters

choropleth_joined_params = dict()

# %%
# call the task


choropleth_joined = (
    join_meeting_counts_to_polygons.set_task_instance_id("choropleth_joined")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        polygons=adjudication_polygons,
        polygon_name_column="Name",
        event_location_column="meeting_location_level_one",
        count_column="meeting_count",
        **choropleth_joined_params,
    )
    .mapvalues(argnames=["events"], argvalues=choropleth_events)
)


# %% [markdown]
# ## Apply Choropleth Colormap

# %%
# parameters

choropleth_colormap_params = dict(
    colormap=...,
    max_classes=...,
    colormap_min=...,
    colormap_max=...,
)

# %%
# call the task


choropleth_colormap = (
    apply_choropleth_colormap.set_task_instance_id("choropleth_colormap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        count_column="meeting_count",
        fill_color_column="fill_color",
        label_column="choropleth_label",
        **choropleth_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=choropleth_joined)
)


# %% [markdown]
# ## Prepare Meeting Count Labels

# %%
# parameters

choropleth_count_labels_params = dict()

# %%
# call the task


choropleth_count_labels = (
    prepare_count_labels.set_task_instance_id("choropleth_count_labels")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        count_column="meeting_count",
        label_column="label",
        suffix=" meetings",
        **choropleth_count_labels_params,
    )
    .mapvalues(argnames=["df"], argvalues=choropleth_colormap)
)


# %% [markdown]
# ## Prepare Polygon Name Labels

# %%
# parameters

choropleth_name_labels_params = dict()

# %%
# call the task


choropleth_name_labels = (
    prepare_polygon_labels.set_task_instance_id("choropleth_name_labels")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(name_column="Name", label_column="label", **choropleth_name_labels_params)
    .mapvalues(argnames=["df"], argvalues=choropleth_colormap)
)


# %% [markdown]
# ## Prepare Missing Location Events

# %%
# parameters

missing_location_events_params = dict()

# %%
# call the task


missing_location_events = (
    prepare_missing_location_events.set_task_instance_id("missing_location_events")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        polygons=adjudication_polygons,
        polygon_name_column="Name",
        event_location_column="meeting_location_level_one",
        label_column="label",
        **missing_location_events_params,
    )
    .mapvalues(argnames=["events"], argvalues=choropleth_events)
)


# %% [markdown]
# ## Create Choropleth Polygon Layer

# %%
# parameters

choropleth_layer_params = dict()

# %%
# call the task


choropleth_layer = (
    create_polygon_layer_pydeck.set_task_instance_id("choropleth_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        layer_style={
            "get_fill_color": "fill_color",
            "get_line_color": [0, 0, 0, 200],
            "line_width_min_pixels": 1,
            "stroked": True,
            "opacity": 0.7,
        },
        legend={
            "label_column": "choropleth_label",
            "color_column": "fill_color",
            "title": "Meetings",
        },
        **choropleth_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=choropleth_colormap)
)


# %% [markdown]
# ## Slim Event Points for Scatter

# %%
# parameters

choropleth_event_points_params = dict()

# %%
# call the task


choropleth_event_points = (
    select_columns.set_task_instance_id("choropleth_event_points")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        columns=["serial_number", "state", "geometry"],
        raise_on_missing=False,
        **choropleth_event_points_params,
    )
    .mapvalues(argnames=["df"], argvalues=choropleth_events)
)


# %% [markdown]
# ## Create Event Locations Scatter Layer

# %%
# parameters

events_scatter_layer_params = dict()

# %%
# call the task


events_scatter_layer = (
    create_scatterplot_layer.set_task_instance_id("events_scatter_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        layer_style={
            "get_fill_color": [255, 140, 0, 200],
            "radius_min_pixels": 5,
            "radius_max_pixels": 8,
            "opacity": 0.8,
            "stroked": True,
            "get_line_color": [255, 255, 255, 180],
            "line_width_min_pixels": 1,
        },
        legend=None,
        **events_scatter_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=choropleth_event_points)
)


# %% [markdown]
# ## Create Polygon Name Label Layer

# %%
# parameters

choropleth_name_layer_params = dict()

# %%
# call the task


choropleth_name_layer = (
    create_text_layer_pydeck.set_task_instance_id("choropleth_name_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        legend=None,
        layer_style={
            "get_text": "label",
            "get_size": 10,
            "get_color": [40, 40, 40, 230],
            "background": False,
            "get_pixel_offset": [0, -10],
        },
        **choropleth_name_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=choropleth_name_labels)
)


# %% [markdown]
# ## Create Meeting Count Label Layer

# %%
# parameters

choropleth_count_layer_params = dict()

# %%
# call the task


choropleth_count_layer = (
    create_text_layer_pydeck.set_task_instance_id("choropleth_count_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        legend=None,
        layer_style={
            "get_text": "label",
            "get_size": 10,
            "get_color": [40, 40, 40, 230],
            "background": False,
            "get_pixel_offset": [0, 10],
        },
        **choropleth_count_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=choropleth_count_labels)
)


# %% [markdown]
# ## Create Missing Location Scatter Layer

# %%
# parameters

missing_scatter_layer_params = dict()

# %%
# call the task


missing_scatter_layer = (
    create_scatterplot_layer.set_task_instance_id("missing_scatter_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        layer_style={
            "get_fill_color": [210, 30, 30, 220],
            "radius_min_pixels": 6,
            "radius_max_pixels": 10,
            "opacity": 0.9,
            "stroked": True,
            "get_line_color": [255, 255, 255, 200],
            "line_width_min_pixels": 1,
        },
        legend=None,
        **missing_scatter_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=missing_location_events)
)


# %% [markdown]
# ## Create Missing Location Label Layer

# %%
# parameters

missing_label_layer_params = dict()

# %%
# call the task


missing_label_layer = (
    create_text_layer_pydeck.set_task_instance_id("missing_label_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        data_url=None,
        legend=None,
        layer_style={
            "get_text": "label",
            "get_size": 11,
            "get_color": [170, 0, 0, 240],
            "background": False,
            "get_pixel_offset": [0, -14],
        },
        **missing_label_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=missing_location_events)
)


# %% [markdown]
# ## Combine All Choropleth Layers

# %%
# parameters

choropleth_geo_layers_params = dict()

# %%
# call the task


choropleth_geo_layers = (
    groupbykey.set_task_instance_id("choropleth_geo_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        iterables=[
            choropleth_layer,
            events_scatter_layer,
            choropleth_name_layer,
            choropleth_count_layer,
            missing_scatter_layer,
            missing_label_layer,
        ],
        **choropleth_geo_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Choropleth View State

# %%
# parameters

choropleth_view_state_params = dict()

# %%
# call the task


choropleth_view_state = (
    create_viewstate_gdf.set_task_instance_id("choropleth_view_state")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=adjudication_polygons,
        padding=0.2,
        viewport_width=1280,
        viewport_height=720,
        **choropleth_view_state_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Choropleth Map

# %%
# parameters

choropleth_map_params = dict(
    widget_id=...,
)

# %%
# call the task


choropleth_map = (
    draw_map.set_task_instance_id("choropleth_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static=False,
        title=None,
        tile_layers=base_maps,
        max_zoom=20,
        view_state=choropleth_view_state,
        legend_style={"placement": "bottom-right"},
        **choropleth_map_params,
    )
    .mapvalues(argnames=["geo_layers"], argvalues=choropleth_geo_layers)
)


# %% [markdown]
# ## Persist Choropleth Map

# %%
# parameters

choropleth_map_html_params = dict(
    filename=...,
)

# %%
# call the task


choropleth_map_html = (
    persist_text.set_task_instance_id("choropleth_map_html")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename_suffix="choropleth_map",
        **choropleth_map_html_params,
    )
    .mapvalues(argnames=["text"], argvalues=choropleth_map)
)


# %% [markdown]
# ## Expand Choropleth to All Group Keys

# %%
# parameters

choropleth_map_html_expanded_params = dict()

# %%
# call the task


choropleth_map_html_expanded = (
    expand_to_composite_keys.set_task_instance_id("choropleth_map_html_expanded")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
        ],
        unpack_depth=1,
    )
    .partial(
        keyed_values=choropleth_map_html,
        reference=grouped_events,
        **choropleth_map_html_expanded_params,
    )
    .call()
)


# %% [markdown]
# ## Choropleth Map Widget

# %%
# parameters

choropleth_map_widget_params = dict()

# %%
# call the task


choropleth_map_widget = (
    create_map_widget_single_view.set_task_instance_id("choropleth_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Meetings per Adjudication", **choropleth_map_widget_params)
    .map(argnames=["view", "data"], argvalues=choropleth_map_html_expanded)
)


# %% [markdown]
# ## Choropleth Map Merged

# %%
# parameters

choropleth_map_merged_params = dict()

# %%
# call the task


choropleth_map_merged = (
    merge_widget_views.set_task_instance_id("choropleth_map_merged")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(widgets=choropleth_map_widget, **choropleth_map_merged_params)
    .call()
)


# %% [markdown]
# ## Box Plot PNG

# %%
# parameters

box_plot_png_params = dict()

# %%
# call the task


box_plot_png = (
    html_to_png.set_task_instance_id("box_plot_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"full_page": False},
        **box_plot_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=box_plot_html)
)


# %% [markdown]
# ## Pie Chart PNG

# %%
# parameters

pie_chart_png_params = dict()

# %%
# call the task


pie_chart_png = (
    html_to_png.set_task_instance_id("pie_chart_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"full_page": False},
        **pie_chart_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=gender_pie_chart_html)
)


# %% [markdown]
# ## Choropleth PNG

# %%
# parameters

choropleth_png_params = dict()

# %%
# call the task


choropleth_png = (
    html_to_png.set_task_instance_id("choropleth_png")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"full_page": False},
        **choropleth_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=choropleth_map_html_expanded)
)


# %% [markdown]
# ## Bundle Report Inputs

# %%
# parameters

report_inputs_params = dict()

# %%
# call the task


report_inputs = (
    groupbykey.set_task_instance_id("report_inputs")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        iterables=[
            grouped_events,
            box_plot_png,
            pie_chart_png,
            choropleth_png,
            topic_location_pivot,
        ],
        **report_inputs_params,
    )
    .call()
)


# %% [markdown]
# ## Generate Community Report

# %%
# parameters

generate_report_params = dict(
    template_path=...,
)

# %%
# call the task


generate_report = (
    generate_community_report.set_task_instance_id("generate_report")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        user_details=user_details,
        time_range=time_range,
        site_url=er_site_url,
        location="Community Area",
        quarter_column="quarter",
        participants_column="participants_total",
        location_column="meeting_location_level_one",
        workflow_title="Community Engagement Report",
        workflow_subtitle="Wildlife Dynamics",
        **generate_report_params,
    )
    .mapvalues(argnames=["report_data"], argvalues=report_inputs)
)


# %% [markdown]
# ## Create Dashboard

# %%
# parameters

dashboard_params = dict(
    warning=...,
)

# %%
# call the task


dashboard = (
    gather_dashboard.set_task_instance_id("dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=[
            total_meetings_merged,
            total_participants_merged,
            median_participants_merged,
            box_plot_merged,
            gender_pie_chart_merged,
            topic_bar_chart_merged,
            choropleth_map_merged,
        ],
        time_range=time_range,
        groupers=groupers,
        **dashboard_params,
    )
    .call()
)
