# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.analysis import dataframe_count as dataframe_count
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import groupbykey as groupbykey
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.groupby import split_groups as split_groups
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.results import (
    merge_widget_views as merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_core.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope_workflows_ext_custom.tasks.io import get_current_user as get_current_user
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_text_layer_pydeck as create_text_layer_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_boxplot as draw_boxplot
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    draw_pie_chart as draw_pie_chart,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import (
    apply_color_map as apply_color_map,
)
from ecoscope_workflows_ext_eden.tasks import add_temporal_idx as add_temporal_idx
from ecoscope_workflows_ext_eden.tasks import (
    apply_choropleth_colormap as apply_choropleth_colormap,
)
from ecoscope_workflows_ext_eden.tasks import (
    build_topic_location_table as build_topic_location_table,
)
from ecoscope_workflows_ext_eden.tasks import compute_median as compute_median
from ecoscope_workflows_ext_eden.tasks import (
    create_viewstate_gdf as create_viewstate_gdf,
)
from ecoscope_workflows_ext_eden.tasks import (
    draw_topic_bar_chart as draw_topic_bar_chart,
)
from ecoscope_workflows_ext_eden.tasks import exclude_groupers as exclude_groupers
from ecoscope_workflows_ext_eden.tasks import (
    expand_to_composite_keys as expand_to_composite_keys,
)
from ecoscope_workflows_ext_eden.tasks import (
    generate_community_report as generate_community_report,
)
from ecoscope_workflows_ext_eden.tasks import get_er_site_url as get_er_site_url
from ecoscope_workflows_ext_eden.tasks import (
    join_meeting_counts_to_polygons as join_meeting_counts_to_polygons,
)
from ecoscope_workflows_ext_eden.tasks import (
    load_adjudication_polygons as load_adjudication_polygons,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_count_labels as prepare_count_labels,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_gender_breakdown as prepare_gender_breakdown,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_missing_location_events as prepare_missing_location_events,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_polygon_labels as prepare_polygon_labels,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "er_client": [],
        "user_details": ["er_client"],
        "er_site_url": ["er_client"],
        "base_maps": [],
        "time_range": [],
        "get_timezone": ["time_range"],
        "groupers": [],
        "events": ["er_client", "time_range"],
        "resolved_events": ["events"],
        "events_tz": ["resolved_events", "get_timezone"],
        "processed_events": ["events_tz", "er_client"],
        "extract_participants_total": ["processed_events"],
        "extract_participants_men": ["extract_participants_total"],
        "extract_participants_women": ["extract_participants_men"],
        "extract_youth_male": ["extract_participants_women"],
        "extract_youth_female": ["extract_youth_male"],
        "extract_location_one": ["extract_youth_female"],
        "events_with_temporal_index": ["extract_location_one", "groupers"],
        "grouped_events": ["events_with_temporal_index", "groupers"],
        "total_meetings": ["grouped_events"],
        "total_meetings_widget": ["total_meetings"],
        "total_meetings_merged": ["total_meetings_widget"],
        "total_participants": ["grouped_events"],
        "total_participants_widget": ["total_participants"],
        "total_participants_merged": ["total_participants_widget"],
        "median_participants": ["grouped_events"],
        "median_participants_widget": ["median_participants"],
        "median_participants_merged": ["median_participants_widget"],
        "box_plot": ["grouped_events"],
        "box_plot_html": ["box_plot"],
        "box_plot_widget": ["box_plot_html"],
        "box_plot_merged": ["box_plot_widget"],
        "gender_breakdown": ["grouped_events"],
        "gender_colormap": ["gender_breakdown"],
        "gender_pie_chart": ["gender_colormap"],
        "gender_pie_chart_html": ["gender_pie_chart"],
        "gender_pie_chart_widget": ["gender_pie_chart_html"],
        "gender_pie_chart_merged": ["gender_pie_chart_widget"],
        "topic_bar_chart": ["grouped_events"],
        "topic_bar_chart_html": ["topic_bar_chart"],
        "topic_bar_chart_widget": ["topic_bar_chart_html"],
        "topic_bar_chart_merged": ["topic_bar_chart_widget"],
        "topic_location_pivot": ["grouped_events"],
        "adjudication_polygons": [],
        "choropleth_groupers": ["groupers"],
        "choropleth_events": ["events_with_temporal_index", "choropleth_groupers"],
        "choropleth_joined": ["adjudication_polygons", "choropleth_events"],
        "choropleth_colormap": ["choropleth_joined"],
        "choropleth_count_labels": ["choropleth_colormap"],
        "choropleth_name_labels": ["choropleth_colormap"],
        "missing_location_events": ["adjudication_polygons", "choropleth_events"],
        "choropleth_layer": ["choropleth_colormap"],
        "choropleth_event_points": ["choropleth_events"],
        "events_scatter_layer": ["choropleth_event_points"],
        "choropleth_name_layer": ["choropleth_name_labels"],
        "choropleth_count_layer": ["choropleth_count_labels"],
        "missing_scatter_layer": ["missing_location_events"],
        "missing_label_layer": ["missing_location_events"],
        "choropleth_geo_layers": [
            "choropleth_layer",
            "events_scatter_layer",
            "choropleth_name_layer",
            "choropleth_count_layer",
            "missing_scatter_layer",
            "missing_label_layer",
        ],
        "choropleth_view_state": ["adjudication_polygons"],
        "choropleth_map": [
            "base_maps",
            "choropleth_view_state",
            "choropleth_geo_layers",
        ],
        "choropleth_map_html": ["choropleth_map"],
        "choropleth_map_html_expanded": ["choropleth_map_html", "grouped_events"],
        "choropleth_map_widget": ["choropleth_map_html_expanded"],
        "choropleth_map_merged": ["choropleth_map_widget"],
        "box_plot_png": ["box_plot_html"],
        "pie_chart_png": ["gender_pie_chart_html"],
        "choropleth_png": ["choropleth_map_html_expanded"],
        "report_inputs": [
            "grouped_events",
            "box_plot_png",
            "pie_chart_png",
            "choropleth_png",
            "topic_location_pivot",
        ],
        "generate_report": [
            "user_details",
            "time_range",
            "er_site_url",
            "report_inputs",
        ],
        "dashboard": [
            "workflow_details",
            "total_meetings_merged",
            "total_participants_merged",
            "median_participants_merged",
            "box_plot_merged",
            "gender_pie_chart_merged",
            "topic_bar_chart_merged",
            "choropleth_map_merged",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "er_client": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client") or {}),
            method="call",
        ),
        "user_details": Node(
            async_task=get_current_user.validate()
            .set_task_instance_id("user_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
            }
            | (params_dict.get("user_details") or {}),
            method="call",
        ),
        "er_site_url": Node(
            async_task=get_er_site_url.validate()
            .set_task_instance_id("er_site_url")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
            }
            | (params_dict.get("er_site_url") or {}),
            method="call",
        ),
        "base_maps": Node(
            async_task=set_base_maps_pydeck.validate()
            .set_task_instance_id("base_maps")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("base_maps") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .set_task_instance_id("groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "events": Node(
            async_task=get_events.validate()
            .set_task_instance_id("events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "event_type",
                    "location",
                    "geometry",
                    "event_details",
                    "state",
                    "serial_number",
                ],
                "include_details": True,
                "raise_on_empty": False,
                "include_updates": False,
                "include_null_geometry": True,
                "include_display_values": True,
                "include_related_events": False,
            }
            | (params_dict.get("events") or {}),
            method="call",
        ),
        "resolved_events": Node(
            async_task=filter_row_values.validate()
            .set_task_instance_id("resolved_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events"),
                "column": "state",
                "values": [
                    "resolved",
                ],
            }
            | (params_dict.get("resolved_events") or {}),
            method="call",
        ),
        "events_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("events_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("resolved_events"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("events_tz") or {}),
            method="call",
        ),
        "processed_events": Node(
            async_task=process_events_details.validate()
            .set_task_instance_id("processed_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_tz"),
                "client": DependsOn("er_client"),
                "map_to_titles": False,
                "ordered": True,
            }
            | (params_dict.get("processed_events") or {}),
            method="call",
        ),
        "extract_participants_total": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_participants_total")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("processed_events"),
                "column_name": "event_details",
                "field_name_options": [
                    "participants_total",
                ],
                "output_column_name": "participants_total",
                "output_type": "float",
            }
            | (params_dict.get("extract_participants_total") or {}),
            method="call",
        ),
        "extract_participants_men": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_participants_men")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_participants_total"),
                "column_name": "event_details",
                "field_name_options": [
                    "participants_men",
                ],
                "output_column_name": "participants_men",
                "output_type": "float",
            }
            | (params_dict.get("extract_participants_men") or {}),
            method="call",
        ),
        "extract_participants_women": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_participants_women")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_participants_men"),
                "column_name": "event_details",
                "field_name_options": [
                    "participants_women",
                ],
                "output_column_name": "participants_women",
                "output_type": "float",
            }
            | (params_dict.get("extract_participants_women") or {}),
            method="call",
        ),
        "extract_youth_male": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_youth_male")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_participants_women"),
                "column_name": "event_details",
                "field_name_options": [
                    "participants_youth_male",
                ],
                "output_column_name": "participants_youth_male",
                "output_type": "float",
            }
            | (params_dict.get("extract_youth_male") or {}),
            method="call",
        ),
        "extract_youth_female": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_youth_female")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_youth_male"),
                "column_name": "event_details",
                "field_name_options": [
                    "participants_youth_female",
                ],
                "output_column_name": "participants_youth_female",
                "output_type": "float",
            }
            | (params_dict.get("extract_youth_female") or {}),
            method="call",
        ),
        "extract_location_one": Node(
            async_task=extract_value_from_json_column.validate()
            .set_task_instance_id("extract_location_one")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_youth_female"),
                "column_name": "event_details",
                "field_name_options": [
                    "meeting_location_level_one",
                ],
                "output_column_name": "meeting_location_level_one",
                "output_type": "str",
            }
            | (params_dict.get("extract_location_one") or {}),
            method="call",
        ),
        "events_with_temporal_index": Node(
            async_task=add_temporal_idx.validate()
            .set_task_instance_id("events_with_temporal_index")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("extract_location_one"),
                "time_col": "time",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("events_with_temporal_index") or {}),
            method="call",
        ),
        "grouped_events": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("grouped_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_with_temporal_index"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("grouped_events") or {}),
            method="call",
        ),
        "total_meetings": Node(
            async_task=dataframe_count.validate()
            .set_task_instance_id("total_meetings")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("total_meetings") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_events"),
            },
        ),
        "total_meetings_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_meetings_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Meetings",
                "decimal_places": 0,
            }
            | (params_dict.get("total_meetings_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("total_meetings"),
            },
        ),
        "total_meetings_merged": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("total_meetings_merged")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("total_meetings_widget"),
            }
            | (params_dict.get("total_meetings_merged") or {}),
            method="call",
        ),
        "total_participants": Node(
            async_task=dataframe_column_sum.validate()
            .set_task_instance_id("total_participants")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column_name": "participants_total",
            }
            | (params_dict.get("total_participants") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_events"),
            },
        ),
        "total_participants_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("total_participants_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Total Participants",
                "decimal_places": 0,
            }
            | (params_dict.get("total_participants_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("total_participants"),
            },
        ),
        "total_participants_merged": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("total_participants_merged")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("total_participants_widget"),
            }
            | (params_dict.get("total_participants_merged") or {}),
            method="call",
        ),
        "median_participants": Node(
            async_task=compute_median.validate()
            .set_task_instance_id("median_participants")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "column": "participants_total",
            }
            | (params_dict.get("median_participants") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_events"),
            },
        ),
        "median_participants_widget": Node(
            async_task=create_single_value_widget_single_view.validate()
            .set_task_instance_id("median_participants_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Median Participants / Meeting",
                "decimal_places": 1,
            }
            | (params_dict.get("median_participants_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("median_participants"),
            },
        ),
        "median_participants_merged": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("median_participants_merged")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("median_participants_widget"),
            }
            | (params_dict.get("median_participants_merged") or {}),
            method="call",
        ),
        "box_plot": Node(
            async_task=draw_boxplot.validate()
            .set_task_instance_id("box_plot")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "y_column": "participants_total",
                "x_column": None,
                "color_column": None,
                "sort_by": None,
                "sort_ascending": True,
                "show_points": "outliers",
                "orientation": "v",
                "boxmode": "overlay",
                "boxmean": False,
                "notched": False,
                "reference_line": None,
                "colormap": "Paired",
                "plot_style": None,
                "layout_style": {
                    "title": None,
                    "yaxis": {
                        "title": "Participants",
                    },
                    "plot_bgcolor": "white",
                },
            }
            | (params_dict.get("box_plot") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("grouped_events"),
            },
        ),
        "box_plot_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("box_plot_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "box_plot",
            }
            | (params_dict.get("box_plot_html") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("box_plot"),
            },
        ),
        "box_plot_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("box_plot_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Participants per Meeting Distribution",
            }
            | (params_dict.get("box_plot_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("box_plot_html"),
            },
        ),
        "box_plot_merged": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("box_plot_merged")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("box_plot_widget"),
            }
            | (params_dict.get("box_plot_merged") or {}),
            method="call",
        ),
        "gender_breakdown": Node(
            async_task=prepare_gender_breakdown.validate()
            .set_task_instance_id("gender_breakdown")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "men_column": "participants_men",
                "women_column": "participants_women",
                "youth_men_column": "participants_youth_male",
                "youth_women_column": "participants_youth_female",
            }
            | (params_dict.get("gender_breakdown") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_events"),
            },
        ),
        "gender_colormap": Node(
            async_task=apply_color_map.validate()
            .set_task_instance_id("gender_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "input_column_name": "category",
                "output_column_name": "gender_color",
                "colormap": "Paired",
            }
            | (params_dict.get("gender_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("gender_breakdown"),
            },
        ),
        "gender_pie_chart": Node(
            async_task=draw_pie_chart.validate()
            .set_task_instance_id("gender_pie_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "value_column": "count",
                "label_column": "category",
                "color_column": "gender_color",
                "plot_style": {
                    "textinfo": "label+percent",
                },
                "layout_style": {
                    "title": None,
                },
            }
            | (params_dict.get("gender_pie_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["dataframe"],
                "argvalues": DependsOn("gender_colormap"),
            },
        ),
        "gender_pie_chart_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("gender_pie_chart_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "gender_pie_chart",
            }
            | (params_dict.get("gender_pie_chart_html") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("gender_pie_chart"),
            },
        ),
        "gender_pie_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("gender_pie_chart_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Men / Women / Youth Men / Youth Women",
            }
            | (params_dict.get("gender_pie_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("gender_pie_chart_html"),
            },
        ),
        "gender_pie_chart_merged": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("gender_pie_chart_merged")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("gender_pie_chart_widget"),
            }
            | (params_dict.get("gender_pie_chart_merged") or {}),
            method="call",
        ),
        "topic_bar_chart": Node(
            async_task=draw_topic_bar_chart.validate()
            .set_task_instance_id("topic_bar_chart")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "event_details_column": "event_details",
                "location_column": "meeting_location_level_one",
                "topic_key": "topics",
                "topic_field": "topic",
                "title": None,
                "x_axis_title": "Location",
                "y_axis_title": "Frequency",
                "colormap": "Paired",
            }
            | (params_dict.get("topic_bar_chart") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_events"),
            },
        ),
        "topic_bar_chart_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("topic_bar_chart_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "topic_bar_chart",
            }
            | (params_dict.get("topic_bar_chart_html") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("topic_bar_chart"),
            },
        ),
        "topic_bar_chart_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("topic_bar_chart_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Topics Covered by Location",
            }
            | (params_dict.get("topic_bar_chart_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("topic_bar_chart_html"),
            },
        ),
        "topic_bar_chart_merged": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("topic_bar_chart_merged")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("topic_bar_chart_widget"),
            }
            | (params_dict.get("topic_bar_chart_merged") or {}),
            method="call",
        ),
        "topic_location_pivot": Node(
            async_task=build_topic_location_table.validate()
            .set_task_instance_id("topic_location_pivot")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "event_details_column": "event_details",
                "location_column": "meeting_location_level_one",
                "topic_key": "topics",
                "topic_field": "topic",
            }
            | (params_dict.get("topic_location_pivot") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("grouped_events"),
            },
        ),
        "adjudication_polygons": Node(
            async_task=load_adjudication_polygons.validate()
            .set_task_instance_id("adjudication_polygons")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("adjudication_polygons") or {}),
            method="call",
        ),
        "choropleth_groupers": Node(
            async_task=exclude_groupers.validate()
            .set_task_instance_id("choropleth_groupers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "groupers": DependsOn("groupers"),
                "exclude": [
                    "meeting_location_level_one",
                ],
            }
            | (params_dict.get("choropleth_groupers") or {}),
            method="call",
        ),
        "choropleth_events": Node(
            async_task=split_groups.validate()
            .set_task_instance_id("choropleth_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_with_temporal_index"),
                "groupers": DependsOn("choropleth_groupers"),
            }
            | (params_dict.get("choropleth_events") or {}),
            method="call",
        ),
        "choropleth_joined": Node(
            async_task=join_meeting_counts_to_polygons.validate()
            .set_task_instance_id("choropleth_joined")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "polygons": DependsOn("adjudication_polygons"),
                "polygon_name_column": "Name",
                "event_location_column": "meeting_location_level_one",
                "count_column": "meeting_count",
            }
            | (params_dict.get("choropleth_joined") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["events"],
                "argvalues": DependsOn("choropleth_events"),
            },
        ),
        "choropleth_colormap": Node(
            async_task=apply_choropleth_colormap.validate()
            .set_task_instance_id("choropleth_colormap")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "count_column": "meeting_count",
                "fill_color_column": "fill_color",
                "label_column": "choropleth_label",
            }
            | (params_dict.get("choropleth_colormap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("choropleth_joined"),
            },
        ),
        "choropleth_count_labels": Node(
            async_task=prepare_count_labels.validate()
            .set_task_instance_id("choropleth_count_labels")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "count_column": "meeting_count",
                "label_column": "label",
                "suffix": " meetings",
            }
            | (params_dict.get("choropleth_count_labels") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("choropleth_colormap"),
            },
        ),
        "choropleth_name_labels": Node(
            async_task=prepare_polygon_labels.validate()
            .set_task_instance_id("choropleth_name_labels")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "name_column": "Name",
                "label_column": "label",
            }
            | (params_dict.get("choropleth_name_labels") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("choropleth_colormap"),
            },
        ),
        "missing_location_events": Node(
            async_task=prepare_missing_location_events.validate()
            .set_task_instance_id("missing_location_events")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "polygons": DependsOn("adjudication_polygons"),
                "polygon_name_column": "Name",
                "event_location_column": "meeting_location_level_one",
                "label_column": "label",
            }
            | (params_dict.get("missing_location_events") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["events"],
                "argvalues": DependsOn("choropleth_events"),
            },
        ),
        "choropleth_layer": Node(
            async_task=create_polygon_layer_pydeck.validate()
            .set_task_instance_id("choropleth_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "layer_style": {
                    "get_fill_color": "fill_color",
                    "get_line_color": [
                        0,
                        0,
                        0,
                        200,
                    ],
                    "line_width_min_pixels": 1,
                    "stroked": True,
                    "opacity": 0.7,
                },
                "legend": {
                    "label_column": "choropleth_label",
                    "color_column": "fill_color",
                    "title": "Meetings",
                },
            }
            | (params_dict.get("choropleth_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("choropleth_colormap"),
            },
        ),
        "choropleth_event_points": Node(
            async_task=select_columns.validate()
            .set_task_instance_id("choropleth_event_points")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "columns": [
                    "serial_number",
                    "state",
                    "geometry",
                ],
                "raise_on_missing": False,
            }
            | (params_dict.get("choropleth_event_points") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("choropleth_events"),
            },
        ),
        "events_scatter_layer": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("events_scatter_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "layer_style": {
                    "get_fill_color": [
                        255,
                        140,
                        0,
                        200,
                    ],
                    "radius_min_pixels": 5,
                    "radius_max_pixels": 8,
                    "opacity": 0.8,
                    "stroked": True,
                    "get_line_color": [
                        255,
                        255,
                        255,
                        180,
                    ],
                    "line_width_min_pixels": 1,
                },
                "legend": None,
            }
            | (params_dict.get("events_scatter_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("choropleth_event_points"),
            },
        ),
        "choropleth_name_layer": Node(
            async_task=create_text_layer_pydeck.validate()
            .set_task_instance_id("choropleth_name_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "legend": None,
                "layer_style": {
                    "get_text": "label",
                    "get_size": 10,
                    "get_color": [
                        40,
                        40,
                        40,
                        230,
                    ],
                    "background": False,
                    "get_pixel_offset": [
                        0,
                        -10,
                    ],
                },
            }
            | (params_dict.get("choropleth_name_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("choropleth_name_labels"),
            },
        ),
        "choropleth_count_layer": Node(
            async_task=create_text_layer_pydeck.validate()
            .set_task_instance_id("choropleth_count_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "legend": None,
                "layer_style": {
                    "get_text": "label",
                    "get_size": 10,
                    "get_color": [
                        40,
                        40,
                        40,
                        230,
                    ],
                    "background": False,
                    "get_pixel_offset": [
                        0,
                        10,
                    ],
                },
            }
            | (params_dict.get("choropleth_count_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("choropleth_count_labels"),
            },
        ),
        "missing_scatter_layer": Node(
            async_task=create_scatterplot_layer.validate()
            .set_task_instance_id("missing_scatter_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "layer_style": {
                    "get_fill_color": [
                        210,
                        30,
                        30,
                        220,
                    ],
                    "radius_min_pixels": 6,
                    "radius_max_pixels": 10,
                    "opacity": 0.9,
                    "stroked": True,
                    "get_line_color": [
                        255,
                        255,
                        255,
                        200,
                    ],
                    "line_width_min_pixels": 1,
                },
                "legend": None,
            }
            | (params_dict.get("missing_scatter_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("missing_location_events"),
            },
        ),
        "missing_label_layer": Node(
            async_task=create_text_layer_pydeck.validate()
            .set_task_instance_id("missing_label_layer")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "data_url": None,
                "legend": None,
                "layer_style": {
                    "get_text": "label",
                    "get_size": 11,
                    "get_color": [
                        170,
                        0,
                        0,
                        240,
                    ],
                    "background": False,
                    "get_pixel_offset": [
                        0,
                        -14,
                    ],
                },
            }
            | (params_dict.get("missing_label_layer") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("missing_location_events"),
            },
        ),
        "choropleth_geo_layers": Node(
            async_task=groupbykey.validate()
            .set_task_instance_id("choropleth_geo_layers")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "iterables": [
                    DependsOn("choropleth_layer"),
                    DependsOn("events_scatter_layer"),
                    DependsOn("choropleth_name_layer"),
                    DependsOn("choropleth_count_layer"),
                    DependsOn("missing_scatter_layer"),
                    DependsOn("missing_label_layer"),
                ],
            }
            | (params_dict.get("choropleth_geo_layers") or {}),
            method="call",
        ),
        "choropleth_view_state": Node(
            async_task=create_viewstate_gdf.validate()
            .set_task_instance_id("choropleth_view_state")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "gdf": DependsOn("adjudication_polygons"),
                "padding": 0.2,
                "viewport_width": 1280,
                "viewport_height": 720,
            }
            | (params_dict.get("choropleth_view_state") or {}),
            method="call",
        ),
        "choropleth_map": Node(
            async_task=draw_map.validate()
            .set_task_instance_id("choropleth_map")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "static": False,
                "title": None,
                "tile_layers": DependsOn("base_maps"),
                "max_zoom": 20,
                "view_state": DependsOn("choropleth_view_state"),
                "legend_style": {
                    "placement": "bottom-right",
                },
            }
            | (params_dict.get("choropleth_map") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers"],
                "argvalues": DependsOn("choropleth_geo_layers"),
            },
        ),
        "choropleth_map_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("choropleth_map_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "filename_suffix": "choropleth_map",
            }
            | (params_dict.get("choropleth_map_html") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("choropleth_map"),
            },
        ),
        "choropleth_map_html_expanded": Node(
            async_task=expand_to_composite_keys.validate()
            .set_task_instance_id("choropleth_map_html_expanded")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "keyed_values": DependsOn("choropleth_map_html"),
                "reference": DependsOn("grouped_events"),
            }
            | (params_dict.get("choropleth_map_html_expanded") or {}),
            method="call",
        ),
        "choropleth_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .set_task_instance_id("choropleth_map_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Meetings per Adjudication",
            }
            | (params_dict.get("choropleth_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("choropleth_map_html_expanded"),
            },
        ),
        "choropleth_map_merged": Node(
            async_task=merge_widget_views.validate()
            .set_task_instance_id("choropleth_map_merged")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("choropleth_map_widget"),
            }
            | (params_dict.get("choropleth_map_merged") or {}),
            method="call",
        ),
        "box_plot_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("box_plot_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "config": {
                    "full_page": False,
                },
            }
            | (params_dict.get("box_plot_png") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["html_path"],
                "argvalues": DependsOn("box_plot_html"),
            },
        ),
        "pie_chart_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("pie_chart_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "config": {
                    "full_page": False,
                },
            }
            | (params_dict.get("pie_chart_png") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["html_path"],
                "argvalues": DependsOn("gender_pie_chart_html"),
            },
        ),
        "choropleth_png": Node(
            async_task=html_to_png.validate()
            .set_task_instance_id("choropleth_png")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "config": {
                    "full_page": False,
                },
            }
            | (params_dict.get("choropleth_png") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["html_path"],
                "argvalues": DependsOn("choropleth_map_html_expanded"),
            },
        ),
        "report_inputs": Node(
            async_task=groupbykey.validate()
            .set_task_instance_id("report_inputs")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "iterables": [
                    DependsOn("grouped_events"),
                    DependsOn("box_plot_png"),
                    DependsOn("pie_chart_png"),
                    DependsOn("choropleth_png"),
                    DependsOn("topic_location_pivot"),
                ],
            }
            | (params_dict.get("report_inputs") or {}),
            method="call",
        ),
        "generate_report": Node(
            async_task=generate_community_report.validate()
            .set_task_instance_id("generate_report")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "output_dir": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
                "user_details": DependsOn("user_details"),
                "time_range": DependsOn("time_range"),
                "site_url": DependsOn("er_site_url"),
                "location": "Community Area",
                "quarter_column": "quarter",
                "participants_column": "participants_total",
                "location_column": "meeting_location_level_one",
                "workflow_title": "Community Engagement Report",
                "workflow_subtitle": "Wildlife Dynamics",
            }
            | (params_dict.get("generate_report") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["report_data"],
                "argvalues": DependsOn("report_inputs"),
            },
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("total_meetings_merged"),
                    DependsOn("total_participants_merged"),
                    DependsOn("median_participants_merged"),
                    DependsOn("box_plot_merged"),
                    DependsOn("gender_pie_chart_merged"),
                    DependsOn("topic_bar_chart_merged"),
                    DependsOn("choropleth_map_merged"),
                ],
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
