# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import dataframe_count as dataframe_count
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_polygon_layer_pydeck as create_polygon_layer_pydeck,
)
from ecoscope.platform.tasks.results import (
    create_scatterplot_layer as create_scatterplot_layer,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_layer_pydeck as create_text_layer_pydeck,
)
from ecoscope.platform.tasks.results import draw_map as draw_map
from ecoscope.platform.tasks.results import draw_pie_chart as draw_pie_chart
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope_workflows_ext_custom.tasks.io import get_current_user as get_current_user
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.io import (
    process_events_details as process_events_details,
)
from ecoscope_workflows_ext_custom.tasks.io import (
    remove_file_scheme as remove_file_scheme,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_boxplot as draw_boxplot
from ecoscope_workflows_ext_custom.tasks.transformation import (
    filter_row_values as filter_row_values,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    select_columns as select_columns,
)
from ecoscope_workflows_ext_eden.tasks import add_temporal_idx as add_temporal_idx
from ecoscope_workflows_ext_eden.tasks import (
    apply_choropleth_colormap as apply_choropleth_colormap,
)
from ecoscope_workflows_ext_eden.tasks import (
    build_topic_location_table as build_topic_location_table,
)
from ecoscope_workflows_ext_eden.tasks import compute_median as compute_median
from ecoscope_workflows_ext_eden.tasks import (
    create_viewstate_gdf as create_viewstate_gdf,
)
from ecoscope_workflows_ext_eden.tasks import (
    draw_topic_bar_chart as draw_topic_bar_chart,
)
from ecoscope_workflows_ext_eden.tasks import exclude_groupers as exclude_groupers
from ecoscope_workflows_ext_eden.tasks import (
    expand_to_composite_keys as expand_to_composite_keys,
)
from ecoscope_workflows_ext_eden.tasks import (
    fix_choropleth_viewport as fix_choropleth_viewport,
)
from ecoscope_workflows_ext_eden.tasks import (
    fix_deck_device_pixel_ratio as fix_deck_device_pixel_ratio,
)
from ecoscope_workflows_ext_eden.tasks import (
    generate_community_report as generate_community_report,
)
from ecoscope_workflows_ext_eden.tasks import get_er_site_url as get_er_site_url
from ecoscope_workflows_ext_eden.tasks import (
    join_meeting_counts_to_polygons as join_meeting_counts_to_polygons,
)
from ecoscope_workflows_ext_eden.tasks import (
    load_adjudication_polygons as load_adjudication_polygons,
)
from ecoscope_workflows_ext_eden.tasks import prepare_age_split as prepare_age_split
from ecoscope_workflows_ext_eden.tasks import (
    prepare_count_labels as prepare_count_labels,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_gender_split as prepare_gender_split,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_missing_location_events as prepare_missing_location_events,
)
from ecoscope_workflows_ext_eden.tasks import (
    prepare_polygon_labels as prepare_polygon_labels,
)
from ecoscope_workflows_ext_eden.tasks import set_int_var as set_int_var
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client") or {}))
        .call()
    )

    user_details = (
        task(get_current_user)
        .validate()
        .set_task_instance_id("user_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("user_details") or {}))
        .call()
    )

    er_site_url = (
        task(get_er_site_url)
        .validate()
        .set_task_instance_id("er_site_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_client, **(params.get("er_site_url") or {}))
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    events = (
        task(get_events)
        .validate()
        .set_task_instance_id("events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "location",
                "geometry",
                "event_details",
                "state",
                "serial_number",
            ],
            include_details=True,
            raise_on_empty=False,
            include_updates=False,
            include_null_geometry=True,
            include_display_values=True,
            include_related_events=False,
            **(params.get("events") or {}),
        )
        .call()
    )

    resolved_events = (
        task(filter_row_values)
        .validate()
        .set_task_instance_id("resolved_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events,
            column="state",
            values=["resolved"],
            **(params.get("resolved_events") or {}),
        )
        .call()
    )

    events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=resolved_events,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("events_tz") or {}),
        )
        .call()
    )

    processed_events = (
        task(process_events_details)
        .validate()
        .set_task_instance_id("processed_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_tz,
            client=er_client,
            map_to_titles=False,
            ordered=True,
            **(params.get("processed_events") or {}),
        )
        .call()
    )

    extract_participants_total = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_participants_total")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=processed_events,
            column_name="event_details",
            field_name_options=["participants_total"],
            output_column_name="participants_total",
            output_type="float",
            **(params.get("extract_participants_total") or {}),
        )
        .call()
    )

    extract_participants_men = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_participants_men")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_participants_total,
            column_name="event_details",
            field_name_options=["participants_men"],
            output_column_name="participants_men",
            output_type="float",
            **(params.get("extract_participants_men") or {}),
        )
        .call()
    )

    extract_participants_women = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_participants_women")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_participants_men,
            column_name="event_details",
            field_name_options=["participants_women"],
            output_column_name="participants_women",
            output_type="float",
            **(params.get("extract_participants_women") or {}),
        )
        .call()
    )

    extract_youth_male = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_youth_male")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_participants_women,
            column_name="event_details",
            field_name_options=["participants_youth_male"],
            output_column_name="participants_youth_male",
            output_type="float",
            **(params.get("extract_youth_male") or {}),
        )
        .call()
    )

    extract_youth_female = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_youth_female")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_youth_male,
            column_name="event_details",
            field_name_options=["participants_youth_female"],
            output_column_name="participants_youth_female",
            output_type="float",
            **(params.get("extract_youth_female") or {}),
        )
        .call()
    )

    extract_location_one = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_location_one")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_youth_female,
            column_name="event_details",
            field_name_options=["meeting_location_level_one"],
            output_column_name="meeting_location_level_one",
            output_type="str",
            **(params.get("extract_location_one") or {}),
        )
        .call()
    )

    extract_meeting_convener = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_meeting_convener")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_location_one,
            column_name="event_details",
            field_name_options=["meeting_convener"],
            output_column_name="meeting_convener",
            output_type="str",
            **(params.get("extract_meeting_convener") or {}),
        )
        .call()
    )

    events_with_temporal_index = (
        task(add_temporal_idx)
        .validate()
        .set_task_instance_id("events_with_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_meeting_convener,
            time_col="time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("events_with_temporal_index") or {}),
        )
        .call()
    )

    grouped_events = (
        task(split_groups)
        .validate()
        .set_task_instance_id("grouped_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_temporal_index,
            groupers=groupers,
            **(params.get("grouped_events") or {}),
        )
        .call()
    )

    total_meetings = (
        task(dataframe_count)
        .validate()
        .set_task_instance_id("total_meetings")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("total_meetings") or {}))
        .mapvalues(argnames=["df"], argvalues=grouped_events)
    )

    total_meetings_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_meetings_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Meetings",
            decimal_places=0,
            **(params.get("total_meetings_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_meetings)
    )

    total_meetings_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_meetings_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_meetings_widget, **(params.get("total_meetings_merged") or {})
        )
        .call()
    )

    total_participants = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_participants")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="participants_total", **(params.get("total_participants") or {})
        )
        .mapvalues(argnames=["df"], argvalues=grouped_events)
    )

    total_participants_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_participants_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Participants",
            decimal_places=0,
            **(params.get("total_participants_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_participants)
    )

    total_participants_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_participants_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_participants_widget,
            **(params.get("total_participants_merged") or {}),
        )
        .call()
    )

    median_participants = (
        task(compute_median)
        .validate()
        .set_task_instance_id("median_participants")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="participants_total", **(params.get("median_participants") or {})
        )
        .mapvalues(argnames=["df"], argvalues=grouped_events)
    )

    median_participants_widget = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("median_participants_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Median Participants / Meeting",
            decimal_places=1,
            **(params.get("median_participants_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=median_participants)
    )

    median_participants_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("median_participants_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=median_participants_widget,
            **(params.get("median_participants_merged") or {}),
        )
        .call()
    )

    box_plot = (
        task(draw_boxplot)
        .validate()
        .set_task_instance_id("box_plot")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            y_column="participants_total",
            x_column=None,
            color_column=None,
            sort_by=None,
            sort_ascending=True,
            show_points="outliers",
            orientation="v",
            boxmode="overlay",
            boxmean=False,
            notched=False,
            reference_line=None,
            colormap="Paired",
            plot_style=None,
            layout_style={
                "title": None,
                "yaxis": {"title": "Participants"},
                "plot_bgcolor": "white",
            },
            **(params.get("box_plot") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=grouped_events)
    )

    box_plot_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("box_plot_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="box_plot",
            **(params.get("box_plot_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=box_plot)
    )

    box_plot_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("box_plot_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Participants per Meeting Distribution",
            **(params.get("box_plot_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=box_plot_html)
    )

    box_plot_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("box_plot_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(widgets=box_plot_widget, **(params.get("box_plot_merged") or {}))
        .call()
    )

    gender_split = (
        task(prepare_gender_split)
        .validate()
        .set_task_instance_id("gender_split")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            total_column="participants_total",
            men_column="participants_men",
            women_column="participants_women",
            **(params.get("gender_split") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_events)
    )

    gender_split_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("gender_split_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="category",
            output_column_name="gender_color",
            colormap="Paired",
            **(params.get("gender_split_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=gender_split)
    )

    gender_split_pie_chart = (
        task(draw_pie_chart)
        .validate()
        .set_task_instance_id("gender_split_pie_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value_column="count",
            label_column="category",
            color_column="gender_color",
            plot_style={"textinfo": "label+percent"},
            layout_style={"title": None},
            **(params.get("gender_split_pie_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=gender_split_colormap)
    )

    gender_split_pie_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("gender_split_pie_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="gender_split_pie_chart",
            **(params.get("gender_split_pie_chart_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=gender_split_pie_chart)
    )

    gender_split_pie_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("gender_split_pie_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Men / Women / Unknown",
            **(params.get("gender_split_pie_chart_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=gender_split_pie_chart_html)
    )

    gender_split_pie_chart_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("gender_split_pie_chart_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=gender_split_pie_chart_widget,
            **(params.get("gender_split_pie_chart_merged") or {}),
        )
        .call()
    )

    age_split = (
        task(prepare_age_split)
        .validate()
        .set_task_instance_id("age_split")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            total_column="participants_total",
            youth_men_column="participants_youth_male",
            youth_women_column="participants_youth_female",
            **(params.get("age_split") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_events)
    )

    age_split_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("age_split_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="category",
            output_column_name="age_color",
            colormap="Paired",
            **(params.get("age_split_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=age_split)
    )

    age_split_pie_chart = (
        task(draw_pie_chart)
        .validate()
        .set_task_instance_id("age_split_pie_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value_column="count",
            label_column="category",
            color_column="age_color",
            plot_style={"textinfo": "label+percent"},
            layout_style={"title": None},
            **(params.get("age_split_pie_chart") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=age_split_colormap)
    )

    age_split_pie_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("age_split_pie_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="age_split_pie_chart",
            **(params.get("age_split_pie_chart_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=age_split_pie_chart)
    )

    age_split_pie_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("age_split_pie_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Youth Men / Youth Women / Adults-Unknown",
            **(params.get("age_split_pie_chart_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=age_split_pie_chart_html)
    )

    age_split_pie_chart_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("age_split_pie_chart_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=age_split_pie_chart_widget,
            **(params.get("age_split_pie_chart_merged") or {}),
        )
        .call()
    )

    topic_bar_chart = (
        task(draw_topic_bar_chart)
        .validate()
        .set_task_instance_id("topic_bar_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event_details_column="event_details",
            location_column="meeting_location_level_one",
            topic_key="topics",
            topic_field="topic",
            title=None,
            x_axis_title="Location",
            y_axis_title="Frequency",
            colormap="Paired",
            **(params.get("topic_bar_chart") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_events)
    )

    topic_bar_chart_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("topic_bar_chart_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="topic_bar_chart",
            **(params.get("topic_bar_chart_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=topic_bar_chart)
    )

    topic_bar_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("topic_bar_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Topics Covered by Location",
            **(params.get("topic_bar_chart_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=topic_bar_chart_html)
    )

    topic_bar_chart_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("topic_bar_chart_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=topic_bar_chart_widget,
            **(params.get("topic_bar_chart_merged") or {}),
        )
        .call()
    )

    topic_location_pivot = (
        task(build_topic_location_table)
        .validate()
        .set_task_instance_id("topic_location_pivot")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            event_details_column="event_details",
            location_column="meeting_location_level_one",
            topic_key="topics",
            topic_field="topic",
            **(params.get("topic_location_pivot") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_events)
    )

    choropleth_groupers = (
        task(exclude_groupers)
        .validate()
        .set_task_instance_id("choropleth_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            exclude=["meeting_location_level_one"],
            **(params.get("choropleth_groupers") or {}),
        )
        .call()
    )

    choropleth_events = (
        task(split_groups)
        .validate()
        .set_task_instance_id("choropleth_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_temporal_index,
            groupers=choropleth_groupers,
            **(params.get("choropleth_events") or {}),
        )
        .call()
    )

    choropleth_event_points = (
        task(select_columns)
        .validate()
        .set_task_instance_id("choropleth_event_points")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=["serial_number", "state", "geometry"],
            raise_on_missing=False,
            **(params.get("choropleth_event_points") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=choropleth_events)
    )

    event_radius = (
        task(set_int_var)
        .validate()
        .set_task_instance_id("event_radius")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("event_radius") or {}))
        .call()
    )

    events_scatter_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("events_scatter_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            legend=None,
            tooltip_columns=["serial_number", "state"],
            layer_style={
                "get_fill_color": [255, 140, 0, 200],
                "get_line_color": [255, 255, 255, 180],
                "opacity": 0.8,
                "stroked": True,
                "line_width_min_pixels": 1,
                "get_radius": event_radius,
                "get_line_width": 1,
                "radius_min_pixels": 5,
                "radius_max_pixels": 8,
                "auto_highlight": False,
                "pickable": True,
            },
            **(params.get("events_scatter_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=choropleth_event_points)
    )

    adjudication_polygons = (
        task(load_adjudication_polygons)
        .validate()
        .set_task_instance_id("adjudication_polygons")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("adjudication_polygons") or {}))
        .call()
    )

    choropleth_joined = (
        task(join_meeting_counts_to_polygons)
        .validate()
        .set_task_instance_id("choropleth_joined")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            polygons=adjudication_polygons,
            polygon_name_column="Name",
            event_location_column="meeting_location_level_one",
            count_column="meeting_count",
            **(params.get("choropleth_joined") or {}),
        )
        .mapvalues(argnames=["events"], argvalues=choropleth_events)
    )

    choropleth_colormap = (
        task(apply_choropleth_colormap)
        .validate()
        .set_task_instance_id("choropleth_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            count_column="meeting_count",
            fill_color_column="fill_color",
            label_column="choropleth_label",
            **(params.get("choropleth_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=choropleth_joined)
    )

    missing_location_events = (
        task(prepare_missing_location_events)
        .validate()
        .set_task_instance_id("missing_location_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            polygons=adjudication_polygons,
            polygon_name_column="Name",
            event_location_column="meeting_location_level_one",
            label_column="label",
            **(params.get("missing_location_events") or {}),
        )
        .mapvalues(argnames=["events"], argvalues=choropleth_events)
    )

    choropleth_layer = (
        task(create_polygon_layer_pydeck)
        .validate()
        .set_task_instance_id("choropleth_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_fill_color": "fill_color",
                "get_line_color": [0, 0, 0, 200],
                "line_width_min_pixels": 1,
                "stroked": True,
                "opacity": 0.7,
            },
            legend={
                "label_column": "choropleth_label",
                "color_column": "fill_color",
                "title": "Meetings",
            },
            tooltip_columns=["Name", "meeting_count", "choropleth_label"],
            **(params.get("choropleth_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=choropleth_colormap)
    )

    missing_scatter_layer = (
        task(create_scatterplot_layer)
        .validate()
        .set_task_instance_id("missing_scatter_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_fill_color": [210, 30, 30, 220],
                "radius_min_pixels": 6,
                "radius_max_pixels": 10,
                "opacity": 0.9,
                "stroked": True,
                "get_line_color": [255, 255, 255, 200],
                "line_width_min_pixels": 1,
            },
            legend=None,
            tooltip_columns=["label", "serial_number"],
            **(params.get("missing_scatter_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=missing_location_events)
    )

    missing_label_layer = (
        task(create_text_layer_pydeck)
        .validate()
        .set_task_instance_id("missing_label_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            legend=None,
            layer_style={
                "get_text": "label",
                "get_size": 11,
                "get_color": [170, 0, 0, 240],
                "background": False,
                "get_pixel_offset": [0, -14],
            },
            tooltip_columns=None,
            **(params.get("missing_label_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=missing_location_events)
    )

    choropleth_name_labels = (
        task(prepare_polygon_labels)
        .validate()
        .set_task_instance_id("choropleth_name_labels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            name_column="Name",
            label_column="label",
            **(params.get("choropleth_name_labels") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=choropleth_colormap)
    )

    text_layer_size = (
        task(set_int_var)
        .validate()
        .set_task_instance_id("text_layer_size")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("text_layer_size") or {}))
        .call()
    )

    choropleth_name_layer = (
        task(create_text_layer_pydeck)
        .validate()
        .set_task_instance_id("choropleth_name_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            legend=None,
            layer_style={
                "get_text": "label",
                "get_size": text_layer_size,
                "get_color": [40, 40, 40, 230],
                "background": False,
                "get_pixel_offset": [0, -10],
            },
            tooltip_columns=None,
            **(params.get("choropleth_name_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=choropleth_name_labels)
    )

    choropleth_count_labels = (
        task(prepare_count_labels)
        .validate()
        .set_task_instance_id("choropleth_count_labels")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            count_column="meeting_count",
            label_column="label",
            suffix=" meetings",
            **(params.get("choropleth_count_labels") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=choropleth_colormap)
    )

    choropleth_count_layer = (
        task(create_text_layer_pydeck)
        .validate()
        .set_task_instance_id("choropleth_count_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            legend=None,
            tooltip_columns=None,
            layer_style={
                "get_text": "label",
                "background": False,
                "get_pixel_offset": [0, 10],
                "get_size": text_layer_size,
                "auto_highlight": False,
                "opacity": 1,
                "word_break": "break-word",
            },
            **(params.get("choropleth_count_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=choropleth_count_labels)
    )

    choropleth_geo_layers = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("choropleth_geo_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[
                choropleth_layer,
                events_scatter_layer,
                choropleth_name_layer,
                choropleth_count_layer,
                missing_scatter_layer,
                missing_label_layer,
            ],
            **(params.get("choropleth_geo_layers") or {}),
        )
        .call()
    )

    choropleth_view_state = (
        task(create_viewstate_gdf)
        .validate()
        .set_task_instance_id("choropleth_view_state")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=adjudication_polygons, **(params.get("choropleth_view_state") or {})
        )
        .call()
    )

    choropleth_map = (
        task(draw_map)
        .validate()
        .set_task_instance_id("choropleth_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static=False,
            title=None,
            tile_layers=base_maps,
            max_zoom=20,
            view_state=choropleth_view_state,
            legend_style={"placement": "bottom-right"},
            output_type="html",
            **(params.get("choropleth_map") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=choropleth_geo_layers)
    )

    choropleth_map_fixed = (
        task(fix_deck_device_pixel_ratio)
        .validate()
        .set_task_instance_id("choropleth_map_fixed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("choropleth_map_fixed") or {}))
        .mapvalues(argnames=["html"], argvalues=choropleth_map)
    )

    choropleth_viewport_fixed = (
        task(fix_choropleth_viewport)
        .validate()
        .set_task_instance_id("choropleth_viewport_fixed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=adjudication_polygons,
            padding=0.2,
            **(params.get("choropleth_viewport_fixed") or {}),
        )
        .mapvalues(argnames=["html"], argvalues=choropleth_map_fixed)
    )

    choropleth_map_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("choropleth_map_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="choropleth_map",
            **(params.get("choropleth_map_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=choropleth_viewport_fixed)
    )

    choropleth_map_html_expanded = (
        task(expand_to_composite_keys)
        .validate()
        .set_task_instance_id("choropleth_map_html_expanded")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            keyed_values=choropleth_map_html,
            reference=grouped_events,
            **(params.get("choropleth_map_html_expanded") or {}),
        )
        .call()
    )

    choropleth_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("choropleth_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Meetings per Adjudication",
            **(params.get("choropleth_map_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=choropleth_map_html_expanded)
    )

    choropleth_map_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("choropleth_map_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=choropleth_map_widget, **(params.get("choropleth_map_merged") or {})
        )
        .call()
    )

    choropleth_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("choropleth_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("choropleth_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=choropleth_map_html_expanded)
    )

    box_plot_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("box_plot_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("box_plot_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=box_plot_html)
    )

    gender_pie_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("gender_pie_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("gender_pie_chart_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=gender_split_pie_chart_html)
    )

    age_pie_chart_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("age_pie_chart_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"full_page": False},
            **(params.get("age_pie_chart_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=age_split_pie_chart_html)
    )

    report_inputs = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("report_inputs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[
                grouped_events,
                box_plot_png,
                gender_pie_chart_png,
                age_pie_chart_png,
                choropleth_png,
                topic_location_pivot,
            ],
            **(params.get("report_inputs") or {}),
        )
        .call()
    )

    norm_output_dir = (
        task(remove_file_scheme)
        .validate()
        .set_task_instance_id("norm_output_dir")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("norm_output_dir") or {}),
        )
        .call()
    )

    generate_report = (
        task(generate_community_report)
        .validate()
        .set_task_instance_id("generate_report")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=norm_output_dir,
            user_details=user_details,
            time_range=time_range,
            site_url=er_site_url,
            location="Community Area",
            quarter_column="quarter",
            participants_column="participants_total",
            location_column="meeting_location_level_one",
            workflow_title="Community Engagement Report",
            workflow_subtitle="Wildlife Dynamics",
            **(params.get("generate_report") or {}),
        )
        .map(argnames=["composite_filter", "report_data"], argvalues=report_inputs)
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_meetings_merged,
                total_participants_merged,
                median_participants_merged,
                box_plot_merged,
                gender_split_pie_chart_merged,
                topic_bar_chart_merged,
                choropleth_map_merged,
                age_split_pie_chart_merged,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
